# Shared tools for Go projects
[tools]
go = "1.23.12"  # Matches CI: cimg/go:1.23

# Fake deps
asterisc = "1.3.0"
kontrol = "1.0.90"
binary_signer = "1.0.4"

# Other tooling
goreleaser-pro = "2.13.3"


[alias]
# These are disabled, but latest mise versions error if they don't have a known
# install source even though it won't ever actually use that source.
asterisc = "ubi:ethereum-optimism/fake-asterisc"
kontrol = "ubi:ethereum-optimism/fake-kontrol"
binary_signer = "ubi:ethereum-optimism/fake-binary_signer"

goreleaser-pro = "ubi:goreleaser/goreleaser-pro[exe=goreleaser]"


[settings]
disable_tools = ["asterisc", "kontrol", "binary_signer"]
