[server]
enable_request_log = true
log_level = "debug"
rpc_host = "0.0.0.0"
rpc_port = 8082

[metrics]
enabled = true
host = "0.0.0.0"
port = 7302

[batch]
max_size = 1000

[cache]
enabled = true

[backend]
max_degraded_latency_threshold = "30ms"
max_retries = 0
out_of_service_seconds = 0
response_timeout_seconds = 5


[backends.bne]
rpc_url = "${UPSTREAM_PROXYD_RPC_URL_2}"
consensus_skip_peer_count = true

[backend_groups]
[backend_groups.replica]
backends = ["bne"]

[rpc_method_mappings]
debug_dbGet = "replica"
debug_getRawReceipts = "replica"
debug_storageRangeAt = "replica"
debug_traceBlockByHash = "replica"
debug_traceBlockByNumber = "replica"
debug_traceTransaction = "replica"
eth_accounts = "replica"
eth_blockNumber = "replica"
eth_call = "replica"
eth_chainId = "replica"
eth_estimateGas = "replica"
eth_feeHistory = "replica"
eth_gasPrice = "replica"
eth_getBalance = "replica"
eth_getBlockByHash = "replica"
eth_getBlockByNumber = "replica"
eth_getBlockRange = "replica"
eth_getBlockReceipts = "replica"
eth_getBlockTransactionCountByHash = "replica"
eth_getBlockTransactionCountByNumber = "replica"
eth_getCode = "replica"
eth_getLogs = "replica"
eth_getProof = "replica"
eth_getStorageAt = "replica"
eth_getTransactionByBlockHashAndIndex = "replica"
eth_getTransactionByHash = "replica"
eth_getTransactionCount = "replica"
eth_getTransactionReceipt = "replica"
eth_getUncleByBlockHashAndIndex = "replica"
eth_maxPriorityFeePerGas = "replica"
eth_sendRawTransaction = "replica"
eth_syncing = "replica"
net_version = "replica"
rollup_getInfo = "replica"
web3_clientVersion = "replica"

