version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0

workflows:
  check-updated-files:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          # 3-column, whitespace-delimited mapping. One mapping per
          # line:
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            op-conductor-mon/.* run-build-op-conductor-mon true
            op-conductor-ops/.* run-build-op-conductor-ops true
            op-signer/.* run-build-op-signer true
            op-txproxy/.* run-build-op-txproxy true
            peer-mgmt-service/.* run-build-pms true
            op-ufm/.* run-build-op-ufm true
            proxyd/.* run-build-proxyd true
            cci-stats/.* run-build-cci-stats true
            op-acceptor/.* run-build-op-acceptor true
            replica-healthcheck/.* run-build-rhc true
            .circleci/.* run-all true
          filters:
            tags:
              only: /.*/

          base-revision: main
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete. In this case, we are using the parent dynamic
          # configuration itself.
          config-path: .circleci/continue_config.yml
