name: op-conductor-mon

on:
  push:
    paths:
      - 'op-conductor-mon/**'
      - '.github/workflows/op-conductor-mon.yml'

jobs:
  build:
    uses: ethereum-optimism/factory/.github/workflows/docker-build.yaml@8a71ef009f8cc2b5284da3ed7642e1fffb59b01e
    with:
      image_name: op-conductor-mon
      context: .
      dockerfile: op-conductor-mon/Dockerfile
      platforms: linux/amd64,linux/arm64
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      gcp_registry: us-docker.pkg.dev/oplabs-tools-artifacts/oss
    permissions:
      contents: read
      id-token: write
      attestations: write
